## Part 1
**TASK1:LOAD AND INSPECT A STRUCTURED DATASET**

In [15]:
# Step 1: Import pandas for Data analysis and manipulation
import pandas as pd

In [16]:
# Step 2: Load the dataset from the URL
URL = "https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Bank%20Churn%20Modelling.csv"

# Load the dataset into a DataFrame
df = pd.read_csv( URL)

# Step 3: Display the first five rows
print("First 5 rows of the dataset:")
display(df.head())

First 5 rows of the dataset:

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [17]:
# Step 4: Display the dataset structure
print("\nDataset structure:")
df.info()

Dataset structure:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerId        10000 non-null  int64
 1   Surname           10000 non-null  object
 2   CreditScore       10000 non-null  int64
 3   Geography         10000 non-null  object
 4   Gender            10000 non-null  object
 5   Age               10000 non-null  int64
 6   Tenure            10000 non-null  int64
 7   Balance           10000 non-null  float64
 8   Num Of Products   10000 non-null  int64
 9   Has Credit Card   10000 non-null  int64
 10  Is Active Member  10000 non-null  int64
 11  Estimated Salary  10000 non-null  float64
 12  Churn             10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

* We have a total of 13 columns
* 2 float64, 8 int64 and 3 string object
* Has Credit Card, Is Active Member and Churn can be classified as binary

In [4]:
# Step 5: Display the list of column names
print("\nColumn names in the dataset:")
print(df.columns.tolist())

Column names in the dataset:
['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'Num Of Products', 'Has Credit Card', 'Is Active Member', 'Estimated Salary', 'Churn']

**TASK 2: : Web Data Acquisition (Screen Scraping)**

In [21]:
# Step 1. Import required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [22]:
# Step 2: Import the requests library
import requests

# Define the URL
url = "https://en.wikipedia.org/wiki/Banking_in_South_Africa"

# Define headers
headers = {"User-Agent": "Mozilla/5.0"}

# Send GET request
response = requests.get(url, headers=headers)

# Check if the request was successful
print(response.status_code)

200

In [23]:
#Step 3: Parse the HTML using BeautifulSoup

from bs4 import BeautifulSoup

# Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# Check the title of the page to confirm parsing worked
#print(soup.title.string)

#print(soup)

In [14]:
# Optionally, preview the first table
first_table = soup.find("table")
print(first_table.prettify()[:500])  # print first 500 characters of the first table

<table class="wikitable sortable">
 <caption>
  Banking financial data in South Africa, in ZAR (as at September 2025)
 </caption>
 <tbody>
  <tr>
   <th>
    Bank
   </th>
   <th>
    <a href="/wiki/Market_capitalization" title="Market capitalization">
     Market capitalization
    </a>
    (billion)
   </th>
   <th>
    Annual
    <a href="/wiki/Revenue" title="Revenue">
     revenue
    </a>
    (billion)
   </th>
   <th>
    Headline
    <a href="/wiki/Earnings" title="Earnings">
     earnin

In [24]:
# Define the function
def get_first_wikitable(url):
    import requests
    from bs4 import BeautifulSoup
    from io import StringIO
    import pandas as pd

    headers = {"User-Agent": "Mozilla/5.0"}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    table_html = str(soup.find("table", {"class": "wikitable"}))
    return pd.read_html(StringIO(table_html), flavor="bs4")[0]

# Call the function
df = get_first_wikitable("https://en.wikipedia.org/wiki/Banking_in_South_Africa")

# Step 5: Display first 5 rows
df.head()

,Bank,Market capitalization (billion),Annual revenue (billion),Headline earnings (billion),HEPS (cents),Tier 1 capital (billion),ROE (%)
0,FNB,448.9,135.7,41.8,748,192.91,20.2
1,Capitec,413.3,35.8,13.7,11912,42.77,29.0
2,Standard Bank,399,181.7,44.5,2691,225.80,18.5
3,ABSA,165.4,109.9,22.1,2662,146.86,14.8
4,Nedbank,105.8,73.5,16.9,2662,101.70,15.8